### ISSUE TITLE
Remove method is not working

### ISSUE THREAD

**Issue by anoubhav** [stephengrice/youtube#2]
I ran the code on python 3.6. However, the find method for a key is still returning it's value even after removing the key( using remove method) on the previous line of code.

d = HashTable()
d.insert('A', 5)
d.insert('B', 10)
d.insert('Ball', 'hello')

print(d.remove('A'))
print(d.remove('A'))
print(d.find('A'))

this is giving the value for the key 'A' all three times. Instead of printing None for the last 2 lines

**Comment by stephengrice** [comment]
Anoubhav, thank you so much for raising this issue. I didn't notice this problem until you pointed it out.

The problem with the HashTable remove method was in the following lines:
```python
# Delete this element in linked list
if prev is None:
	node = None
else:
	prev.next = prev.next.next
```

The issue was twofold:

1) `node = None` : The function sets a local variable to None instead of actually using the `buckets` array. Since the locally scoped variable is discarded after the function returns, this assignment statement has no effect on the data structure itself. The outcome would be the same with or without this line.

2) Setting the variable to `None` presents another problem. Since each node is a Linked List, any children stored in `node.next` will be lost as a result of this assignment. Instead, it should be set to `node.next` in order to preserve children. The property will be set to `None` anyway if there are no children.

I know you probably understand this, but I wanted to explain the issue for anyone else who may run into this same problem.

Thanks again!
